In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [42]:
!pip install imbalanced-learn

In [2]:
data = pd.read_csv(r'C:\Users\deva0\Downloads/general_data.csv')

In [3]:
data.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   51        No      Travel_Rarely                   Sales                 6   
1   31       Yes  Travel_Frequently  Research & Development                10   
2   32        No  Travel_Frequently  Research & Development                17   
3   38        No         Non-Travel  Research & Development                 2   
4   32        No      Travel_Rarely  Research & Development                10   

   Education EducationField  EmployeeCount  EmployeeID  Gender  ...  \
0          2  Life Sciences              1           1  Female  ...   
1          1  Life Sciences              1           2  Female  ...   
2          4          Other              1           3    Male  ...   
3          5  Life Sciences              1           4    Male  ...   
4          1        Medical              1           5    Male  ...   

   NumCompaniesWorked Over18 PercentSalaryHike  StandardHours  \
0                 1.0      Y                11              8   
1                 0.0      Y                23              8   
2                 1.0      Y                15              8   
3                 3.0      Y                11              8   
4                 4.0      Y                12              8   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                 0               1.0                      6               1   
1                 1               6.0                      3               5   
2                 3               5.0                      2               5   
3                 3              13.0                      5               8   
4                 2               9.0                      2               6   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  
2                        0                     3  
3                        7                     5  
4                        0                     4  

[5 rows x 24 columns]

In [6]:
data['NumCompaniesWorked'] = data['NumCompaniesWorked'].fillna(0)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      4410 non-null   int64  
 1   Attrition                4410 non-null   object 
 2   BusinessTravel           4410 non-null   object 
 3   Department               4410 non-null   object 
 4   DistanceFromHome         4410 non-null   int64  
 5   Education                4410 non-null   int64  
 6   EducationField           4410 non-null   object 
 7   EmployeeCount            4410 non-null   int64  
 8   EmployeeID               4410 non-null   int64  
 9   Gender                   4410 non-null   object 
 10  JobLevel                 4410 non-null   int64  
 11  JobRole                  4410 non-null   object 
 12  MaritalStatus            4410 non-null   object 
 13  MonthlyIncome            4410 non-null   int64  
 14  NumCompaniesWorked      

In [9]:
data['TotalWorkingYears'] = data['TotalWorkingYears'].fillna(0)

In [15]:
data.drop(columns=  ['EmployeeCount','Over18'],inplace = True) 

### Encoding

In [16]:
numerical_cols = []
categorial_cols = []
for i in data.columns:
    if data[i].dtype == 'O':
        categorial_cols.append(i)
    else:
        numerical_cols.append(i)

In [17]:
numerical_cols

['Age',
 'DistanceFromHome',
 'Education',
 'EmployeeID',
 'JobLevel',
 'MonthlyIncome',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'YearsAtCompany',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [18]:
categorial_cols

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus']

In [20]:
data_cat = data[categorial_cols]

In [25]:
data_num = data[numerical_cols]

In [21]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [23]:
for i in data_cat.columns:
    data_cat[i] = enc.fit_transform(data_cat[i])

C:\Users\deva0\AppData\Local\Temp\ipykernel_20364\714389247.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cat[i] = enc.fit_transform(data_cat[i])
C:\Users\deva0\AppData\Local\Temp\ipykernel_20364\714389247.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cat[i] = enc.fit_transform(data_cat[i])
C:\Users\deva0\AppData\Local\Temp\ipykernel_20364\714389247.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] 

In [24]:
data_cat.head()

Attrition  BusinessTravel  Department  EducationField  Gender  JobRole  \
0          0               2           2               1       0        0   
1          1               1           1               1       0        6   
2          0               1           1               4       1        7   
3          0               0           1               1       1        1   
4          0               2           1               3       1        7   

   MaritalStatus  
0              1  
1              2  
2              1  
3              1  
4              2

In [26]:
#concatenation of two dataframes

data_processed = pd.concat([data_num,data_cat] , axis=1)

In [80]:
data_processed.head()

Age  DistanceFromHome  Education  EmployeeID  JobLevel  MonthlyIncome  \
0   51                 6          2           1         1         131160   
1   31                10          1           2         1          41890   
2   32                17          4           3         4         193280   
3   38                 2          5           4         3          83210   
4   32                10          1           5         1          23420   

   NumCompaniesWorked  PercentSalaryHike  StockOptionLevel  TotalWorkingYears  \
0                 1.0                 11                 0                1.0   
1                 0.0                 23                 1                6.0   
2                 1.0                 15                 3                5.0   
3                 3.0                 11                 3               13.0   
4                 4.0                 12                 2                9.0   

   ...  YearsAtCompany  YearsSinceLastPromotion  YearsWithCurrManager  \
0  ...               1                        0                     0   
1  ...               5                        1                     4   
2  ...               5                        0                     3   
3  ...               8                        7                     5   
4  ...               6                        0                     4   

   Attrition  BusinessTravel  Department  EducationField  Gender  JobRole  \
0          0               2           2               1       0        0   
1          1               1           1               1       0        6   
2          0               1           1               4       1        7   
3          0               0           1               1       1        1   
4          0               2           1               3       1        7   

   MaritalStatus  
0              1  
1              2  
2              1  
3              1  
4              2  

[5 rows x 21 columns]

In [79]:
data_processed.drop(columns='StandardHours' , inplace=True)

### logistic model without feature cut down

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report,f1_score

In [99]:
X = data_processed.drop(columns=['Attrition'])
y = data_processed['Attrition']

In [103]:
lr_model = LogisticRegression()

In [32]:
x_train , x_test, y_train, y_test = train_test_split(X,y,test_size= 0.2)
lr_model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\deva0\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

performance of the Model

In [33]:
y_pred = model.predict(x_test)

In [34]:
confusion_matrix(y_pred = y_pred , y_true = y_test)

array([[734,   0],
       [148,   0]], dtype=int64)

In [35]:
accuracy_score(y_pred= y_pred , y_true = y_test)

0.8321995464852607

In [36]:
model.score(x_train,y_train)

0.8404195011337868

In [37]:
precision_score(y_pred = y_pred , y_true = y_test)

C:\Users\deva0\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.0

In [38]:
recall_score(y_pred=y_pred,y_true=y_test)

0.0

In [52]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.60      0.89      0.72       493
           1       0.65      0.25      0.36       389

    accuracy                           0.61       882
   macro avg       0.62      0.57      0.54       882
weighted avg       0.62      0.61      0.56       882



### class imbalance 

In [39]:
data_processed['Attrition'].value_counts()

0    3699
1     711
Name: Attrition, dtype: int64

### Smote

In [43]:
from imblearn.over_sampling import SMOTE

In [49]:
from sklearn.metrics import classification_report

In [100]:
x_train , x_test, y_train, y_test = train_test_split(X,y,test_size= 0.2)

In [44]:
smote = SMOTE(random_state=42)

In [101]:
x_resampled , y_resampled = smote.fit_resample(x_train,y_train)

In [104]:
lr_model.fit(x_resampled , y_resampled)

LogisticRegression()

In [106]:
y_pred = lr_model.predict(x_test)

In [107]:
confusion_matrix(y_pred= y_pred , y_true = y_test)

array([[426, 307],
       [ 57,  92]], dtype=int64)

In [108]:
accuracy_score(y_pred= y_pred , y_true= y_test)

0.5873015873015873

In [109]:
precision_score(y_pred = y_pred, y_true= y_test)

0.23057644110275688

In [110]:
recall_score(y_pred = y_pred, y_true= y_test)

0.6174496644295302

### undersampling

In [57]:
from imblearn.under_sampling import RandomUnderSampler

In [133]:
X = data_processed.drop(columns=['Attrition'])
y = data_processed['Attrition']

In [134]:
x_train , x_test, y_train, y_test = train_test_split(X,y,test_size= 0.2)

In [58]:
under_sampler = RandomUnderSampler()

In [135]:
x_undersample , y_undersample = under_sampler.fit_resample(x_train , y_train)

In [113]:
lr_model.fit(x_undersample , y_undersample)

LogisticRegression()

In [114]:
y_pred = lr_model.predict(x_test)

In [115]:
confusion_matrix(y_pred = y_pred, y_true = y_test)

array([[428, 308],
       [ 48,  98]], dtype=int64)

In [116]:
accuracy_score(y_pred = y_pred, y_true = y_test)

0.5963718820861678

In [117]:
precision_score(y_pred = y_pred, y_true= y_test)

0.2413793103448276

In [118]:
recall_score(y_pred = y_pred, y_true= y_test)

0.6712328767123288

### Feature Scaling with Z-score standardization

In [149]:
X = data_processed.drop(columns=['Attrition'])
y = data_processed['Attrition']

In [119]:
from sklearn.preprocessing import StandardScaler

In [151]:
scalar = StandardScaler()

In [152]:
X_standarised = scalar.fit_transform(X)

In [153]:
x_train , x_test, y_train, y_test = train_test_split(X_standarised,y,test_size= 0.2)

In [154]:
lr_model.fit(x_train,y_train)

LogisticRegression()

In [155]:
y_pred = lr_model.predict(x_test)

In [156]:
confusion_matrix(y_pred=y_pred,y_true = y_test)

array([[722,   0],
       [156,   4]], dtype=int64)

In [157]:
precision_score(y_pred = y_pred , y_true = y_test)

1.0

In [158]:
recall_score(y_pred = y_pred , y_true = y_test)

0.025

In [159]:
accuracy_score(y_pred = y_pred ,y_true = y_test)

0.8231292517006803

In [161]:
coefficients = lr_model.coef_[0]

In [162]:
feature_names = X.columns

In [164]:
coefficients_df = pd.DataFrame({'Feature': feature_names , 'Coefficient':coefficients})

In [165]:
coefficients_df

Feature  Coefficient
0                       Age    -0.275080
1          DistanceFromHome    -0.025927
2                 Education    -0.061275
3                EmployeeID    -0.024026
4                  JobLevel    -0.015527
5             MonthlyIncome    -0.065152
6        NumCompaniesWorked     0.304780
7         PercentSalaryHike     0.068885
8          StockOptionLevel    -0.012899
9         TotalWorkingYears    -0.470960
10    TrainingTimesLastYear    -0.210089
11           YearsAtCompany     0.212997
12  YearsSinceLastPromotion     0.375265
13     YearsWithCurrManager    -0.543165
14           BusinessTravel     0.018298
15               Department    -0.096025
16           EducationField    -0.110733
17                   Gender     0.025263
18                  JobRole     0.107848
19            MaritalStatus     0.331741

In [167]:
soreted_df = coefficients_df.reindex(coefficients_df['Coefficient'].abs().sort_values(ascending=False).index)

In [169]:
soreted_df

Feature  Coefficient
13     YearsWithCurrManager    -0.543165
9         TotalWorkingYears    -0.470960
12  YearsSinceLastPromotion     0.375265
19            MaritalStatus     0.331741
6        NumCompaniesWorked     0.304780
0                       Age    -0.275080
11           YearsAtCompany     0.212997
10    TrainingTimesLastYear    -0.210089
16           EducationField    -0.110733
18                  JobRole     0.107848
15               Department    -0.096025
7         PercentSalaryHike     0.068885
5             MonthlyIncome    -0.065152
2                 Education    -0.061275
1          DistanceFromHome    -0.025927
17                   Gender     0.025263
3                EmployeeID    -0.024026
14           BusinessTravel     0.018298
4                  JobLevel    -0.015527
8          StockOptionLevel    -0.012899

In [172]:
k=5
top_features = soreted_df['Feature'][:k].tolist()

In [173]:
print(f'Top {k} features :{top_features}')

Top 5 features :['YearsWithCurrManager', 'TotalWorkingYears', 'YearsSinceLastPromotion', 'MaritalStatus', 'NumCompaniesWorked']


## Random Forest Model

In [66]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
x_train , x_test, y_train, y_test = train_test_split(X,y,test_size= 0.2)

In [68]:
model = RandomForestClassifier()

In [83]:
model.fit(x_train , y_train)

RandomForestClassifier()

In [84]:
y_pred = model.predict(x_test)

In [85]:
confusion_matrix(y_pred = y_pred, y_true = y_test)

array([[735,   0],
       [ 17, 130]], dtype=int64)

In [86]:
accuracy_score(y_pred=y_pred,y_true = y_test)

0.9807256235827665

In [87]:
precision_score(y_pred = y_pred ,y_true = y_test)

1.0

In [88]:
recall_score(y_pred = y_pred ,y_true = y_test)

0.8843537414965986

In [89]:
f1_score(y_pred = y_pred , y_true = y_test)

0.9386281588447652

## Decision Tree Classifier

In [90]:
from sklearn.tree import DecisionTreeClassifier

In [91]:
d_model = DecisionTreeClassifier()

In [92]:
d_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [93]:
y_pred = d_model.predict(x_test)

In [94]:
confusion_matrix(y_pred = y_pred, y_true = y_test)

array([[726,   9],
       [ 11, 136]], dtype=int64)

In [95]:
accuracy_score(y_pred=y_pred,y_true = y_test)

0.9773242630385488

In [96]:
recall_score(y_pred = y_pred ,y_true = y_test)

0.9251700680272109

In [97]:
f1_score(y_pred = y_pred , y_true = y_test)

0.9315068493150684

In [98]:
precision_score(y_pred = y_pred ,y_true = y_test)

0.9379310344827586

### dashboard using plotly

In [174]:
import dash
import dash_core_components as dcc
import dash_html_components as html

C:\Users\deva0\AppData\Local\Temp\ipykernel_20364\954449312.py:2: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
C:\Users\deva0\AppData\Local\Temp\ipykernel_20364\954449312.py:3: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html


In [177]:
app = dash.Dash()
app.title = ''
app.layout = html.Div([
    html.H1('KPIs Dashboard of XYZ company',style = {'text-align':'center'}),
    dcc.Graph()
])







if __name__ == '__main__':
    app.run_server(debug= True,port = 8050)